# Databricks notebook source
# MAGIC %md
# MAGIC # 01 — Load Bronze From SQL (WorkspaceClient + Statement Execution API)
# MAGIC
# MAGIC Reads every `data/*.sql` file generated by notebook `00_generate_bronze_sql` and
# MAGIC executes each statement against the SQL Warehouse via the modern
# MAGIC `databricks-sdk` Statement Execution API. No 1 MB file-size limit (unlike SQL
# MAGIC job tasks). Idempotent — each file starts with `CREATE TABLE IF NOT EXISTS` +
# MAGIC `TRUNCATE`.

# COMMAND ----------
# databricks-sdk is installed via the job environment spec in resources/jobs.yml.

# COMMAND ----------
dbutils.widgets.text("catalog", "retail_consumer_goods")
dbutils.widgets.text("schema", "network_anomaly_graph")
dbutils.widgets.text("data_dir", "")
dbutils.widgets.text("warehouse_id", "")
CATALOG = dbutils.widgets.get("catalog")
SCHEMA = dbutils.widgets.get("schema")
DATA_DIR = dbutils.widgets.get("data_dir")
WAREHOUSE_ID = dbutils.widgets.get("warehouse_id")

import os
if not DATA_DIR:
    NB = dbutils.notebook.entry_point.getDbutils().notebook().getContext().notebookPath().get()
    DATA_DIR = "/Workspace" + os.path.dirname(os.path.dirname(NB)) + "/data"
print(f"Loading bronze SQL from: {DATA_DIR}")
print(f"Target: {CATALOG}.{SCHEMA}")
print(f"Warehouse: {WAREHOUSE_ID}")

# COMMAND ----------
import re
import time
from databricks.sdk import WorkspaceClient
from databricks.sdk.service.sql import StatementState

w = WorkspaceClient()
print(f"databricks-sdk version: {__import__('databricks.sdk').sdk.__version__ if hasattr(__import__('databricks.sdk').sdk, '__version__') else 'unknown'}")

# Discover the SQL files
files = sorted(f.path for f in dbutils.fs.ls(DATA_DIR) if f.path.endswith(".sql"))
assert files, f"No .sql files found under {DATA_DIR}. Run notebook 00 first."
print(f"Files to execute: {len(files)}")
for p in files:
    print(f"  {p}")

# COMMAND ----------
# Split SQL files into individual statements. Statements end with `;` followed by
# newline-or-EOF — this preserves any `;` embedded in strings.
STATEMENT_SPLIT = re.compile(r";\s*(?:\r?\n|$)")

def split_statements(sql_text: str):
    parts = STATEMENT_SPLIT.split(sql_text)
    return [p.strip() for p in parts if p.strip()]


def run_statement(stmt: str, max_wait_s: int = 120) -> None:
    """Execute one SQL statement and block until it succeeds (or raises)."""
    resp = w.statement_execution.execute_statement(
        statement=stmt,
        warehouse_id=WAREHOUSE_ID,
        catalog=CATALOG,
        schema=SCHEMA,
        wait_timeout="50s",  # synchronous up to 50s, then return PENDING token
    )
    stmt_id = resp.statement_id
    state = resp.status.state if resp.status else None
    waited = 0
    while state in (StatementState.PENDING, StatementState.RUNNING):
        time.sleep(2)
        waited += 2
        if waited > max_wait_s:
            raise TimeoutError(f"Statement {stmt_id} still {state} after {max_wait_s}s")
        resp = w.statement_execution.get_statement(stmt_id)
        state = resp.status.state
    if state != StatementState.SUCCEEDED:
        err = resp.status.error.message if resp.status and resp.status.error else "unknown error"
        raise RuntimeError(f"Statement {stmt_id} ended in {state}: {err}\n  SQL preview: {stmt[:200]}…")


total = 0
for path in files:
    raw = dbutils.fs.head(path, 100 * 1024 * 1024)  # up to 100 MB per file
    statements = split_statements(raw)
    name = os.path.basename(path)
    print(f"\n=== {name} — {len(statements)} statements ===")
    for i, stmt in enumerate(statements):
        run_statement(stmt)
    print(f"  ✓ {len(statements)} statements OK")
    total += len(statements)
print(f"\nTotal statements executed: {total}")

# COMMAND ----------
# MAGIC %md ## Row-count sanity check

# COMMAND ----------
checks = []
for tbl in ["bronze_subnets", "bronze_hosts", "bronze_services", "bronze_network_flows", "bronze_dns_queries"]:
    n = spark.table(f"{CATALOG}.{SCHEMA}.{tbl}").count()
    checks.append((tbl, n))
    print(f"  {tbl:.<35} {n:>8,}")
assert all(n > 0 for _, n in checks), f"One or more bronze tables is empty: {checks}"
dbutils.notebook.exit(str(checks))
